[graphics]
resolution = "720p"
fullscreen = false
vsync = true
fov = 60
debug = false # Only in debug builds

[telemetry]
logging = "debug"
profiling = false

[dev-mode] # Only in dev builds
enabled = true
reload-interval = 5.0

[game]
sources = ["game.data", "game/", "common/"]
modules = "modules.toml"
config = "game.toml"
