[graphics]
resolution = "720p"
fullscreen = true
vsync = false
fov = 60
debug = false # Only in debug builds

[telemetry]
# trace, debug, info, warn, error, off. Both trace and debug are only available in debug builds.
logging = "debug"

[dev-mode] # Only in dev builds
enabled = true
reload-interval = 5.0

[game]
sources = ["game.data", "game/", "common/"]
modules = "modules.toml"
config = "game.toml"
