
[[entity]]
    [entity.named]
        name = "test1"
    [entity.position]
        point = {x = 11.0, y = 12.0, z = 13.0}

[[entity]]
    [entity.named]
        name = "test2"
    [entity.position]
        point = {x = 14.0, y = 15.0, z = 15.0}
    [entity.transform]
        rotation = {x = 1.0, y = 0.5, z = 1.2}
        scale = {x = 1.0, y = 1.0, z = 1.0}

[[entity]]
    [entity.named]
        name = "sprite-test"
    [entity.position]
        point = {x = 0.0, y = 0.0, z = 0.0}
    [entity.sprite]
    