
[[entity]]
    [entity.named]
        name = "test1"
    [entity.position]
        x = 11.0
        y = 12.0
        z = 13.0

[[entity]]
    [entity.named]
        name = "test2"
    [entity.position]
        x = 14.0
        y = 15.0
        z = 15.0