[[module]]
    path = "modules/"
    name = "test"
    enabled = false
    required = true

[[module]]
    path = "modules/"
    name = "test2"
    enabled = false

[[module]]
    path = "modules/"
    name = "editor"
    enabled = true