[imgui]
default = "dark" # "dark", "light" or "classic"

# Colors: {rgb = "hex-color", opacity = <opacity>} or simply "hex-color" (opacity defaults to 1.0)

[colors.window]
base = "#1a1b1c"

[colors.header]
base = "#4E5905"
hovered = "#92A60A"
active = "#D5F30F"

[colors.button]
base = "#333436"
hovered = "#4d4e4f"
active = "#262627"

[colors.frame]
base = "#333436"
hovered = "#4d4e4f"
active = "#262627"

[colors.tab]
base = "#262627"
hovered = "#92A60A"
active = "#4E5905"
unfocused = "#474848"
unfocused-active = "#4E5905"

[colors.title]
base = "#262627"
active = "#262627"
collapsed = "#262627"
